kind: pipeline
name: default

steps:
- name: build
  image: golang:1.17
  commands:
    - go get gopkg.in/yaml.v2
    - go get github.com/shirou/gopsutil/disk
    - GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -o ${DRONE_REPO_NAME}_${GOOS}_${GOARCH}.exe
    - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o ${DRONE_REPO_NAME}_${GOOS}_${GOARCH}
    - GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -o ${DRONE_REPO_NAME}_${GOOS}_${GOARCH}
    - GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -o ${DRONE_REPO_NAME}_${GOOS}_${GOARCH}
    - GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o ${DRONE_REPO_NAME}_${GOOS}_${GOARCH}

- name: github release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: GITHUB_TOKEN
    files:
      - ${DRONE_REPO_NAME}_*
    checksum:
      - sha256
  when:
    event:
      - tag

trigger:
  event:
    - tag
