kind: pipeline
name: default

steps:
- name: build
  image: golang:1.17
  commands:
    - go get gopkg.in/yaml.v2
    - go get github.com/shirou/gopsutil/disk
    - GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -o ${DRONE_REPO_NAME}_${DRONE_TAG}_windows_amd64.exe
    - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o ${DRONE_REPO_NAME}_${DRONE_TAG}_linux_amd64
    - GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -o ${DRONE_REPO_NAME}_${DRONE_TAG}_darwin_amd64
    - GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -o ${DRONE_REPO_NAME}_${DRONE_TAG}_darwin_arm64
    - GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o ${DRONE_REPO_NAME}_${DRONE_TAG}_linux_arm64

- name: github release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: GITHUB_TOKEN
    files:
      - ${DRONE_REPO_NAME}_*
    checksum:
      - sha256
  when:
    event:
      - tag

trigger:
  event:
    - tag
